apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: johndiddles/hngdockertask1-fe:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: react-fastapi-config
                  key: REACT_APP_API_URL
            - name: REACT_APP_LESSON_DAY
              valueFrom:
                configMapKeyRef:
                  name: react-fastapi-config
                  key: REACT_APP_LESSON_DAY

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  # type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30000
